sonar.projectKey=WaveCRM
sonar.projectName=Wave CRM
sonar.projectVersion=0.1.0
sonar.sourceEncoding=UTF-8

sonar.sources=apps/api/src,apps/web/app,apps/web/components,apps/web/lib,packages/database/src,packages/database/prisma
sonar.tests=apps/api/test,apps/web/lib
sonar.test.inclusions=apps/api/test/**/*.test.cjs,apps/web/lib/**/*.test.mjs

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,packages/database/prisma/migrations/**,apps/web/lib/**/*.test.mjs
sonar.coverage.exclusions=**/*.d.ts,**/*.config.*,apps/api/src/main.ts,apps/api/src/**/**.module.ts,apps/web/app/**/layout.tsx
sonar.javascript.lcov.reportPaths=coverage/api/lcov.info,coverage/web/lcov.info
sonar.scm.provider=git
