// Fuente: Clasificador Geografico Estadistico 2025 del INEC.
export const CANTONS_BY_PROVINCE = {
  Azuay: [
    "Cuenca",
    "Gir\u00f3n",
    "Gualaceo",
    "Nab\u00f3n",
    "Paute",
    "Pucar\u00e1",
    "San Fernando",
    "Santa Isabel",
    "S\u00edgsig",
    "O\u00f1a",
    "Chordeleg",
    "El Pan",
    "Sevilla de Oro",
    "Guachapala",
    "Camilo Ponce Enr\u00edquez",
  ],
  "Bol\u00edvar": [
    "Guaranda",
    "Chillanes",
    "Chimbo",
    "Echeand\u00eda",
    "San Miguel",
    "Caluma",
    "Las Naves",
  ],
  "Ca\u00f1ar": [
    "Azogues",
    "Bibli\u00e1n",
    "Ca\u00f1ar",
    "La Troncal",
    "El Tambo",
    "D\u00e9leg",
    "Suscal",
  ],
  Carchi: [
    "Tulc\u00e1n",
    "Bol\u00edvar",
    "Espejo",
    "Mira",
    "Mont\u00fafar",
    "San Pedro de Huaca",
  ],
  Cotopaxi: [
    "Latacunga",
    "La Man\u00e1",
    "Pangua",
    "Pujil\u00ed",
    "Salcedo",
    "Saquisil\u00ed",
    "Sigchos",
  ],
  Chimborazo: [
    "Riobamba",
    "Alaus\u00ed",
    "Colta",
    "Chambo",
    "Chunchi",
    "Guamote",
    "Guano",
    "Pallatanga",
    "Penipe",
    "Cumand\u00e1",
  ],
  "El Oro": [
    "Machala",
    "Arenillas",
    "Atahualpa",
    "Balsas",
    "Chilla",
    "El Guabo",
    "Huaquillas",
    "Marcabel\u00ed",
    "Pasaje",
    "Pi\u00f1as",
    "Portovelo",
    "Santa Rosa",
    "Zaruma",
    "Las Lajas",
  ],
  Esmeraldas: [
    "Esmeraldas",
    "Eloy Alfaro",
    "Muisne",
    "Quinind\u00e9",
    "San Lorenzo",
    "Atacames",
    "Rioverde",
  ],
  Guayas: [
    "Guayaquil",
    "Alfredo Baquerizo Moreno (Juj\u00e1n)",
    "Balao",
    "Balzar",
    "Colimes",
    "Daule",
    "Dur\u00e1n",
    "El Empalme",
    "El Triunfo",
    "Milagro",
    "Naranjal",
    "Naranjito",
    "Palestina",
    "Pedro Carbo",
    "Samborond\u00f3n",
    "Santa Luc\u00eda",
    "Salitre",
    "San Jacinto de Yaguachi",
    "Playas",
    "Sim\u00f3n Bol\u00edvar",
    "Coronel Marcelino Maridue\u00f1a",
    "Lomas de Sargentillo",
    "Nobol",
    "General Antonio Elizalde",
    "Isidro Ayora",
  ],
  Imbabura: [
    "Ibarra",
    "Antonio Ante",
    "Cotacachi",
    "Otavalo",
    "Pimampiro",
    "San Miguel de Urcuqu\u00ed",
  ],
  Loja: [
    "Loja",
    "Calvas",
    "Catamayo",
    "Celica",
    "Chaguarpamba",
    "Esp\u00edndola",
    "Gonzanam\u00e1",
    "Macar\u00e1",
    "Paltas",
    "Puyango",
    "Saraguro",
    "Sozoranga",
    "Zapotillo",
    "Pindal",
    "Quilanga",
    "Olmedo",
  ],
  "Los R\u00edos": [
    "Babahoyo",
    "Baba",
    "Montalvo",
    "Puebloviejo",
    "Quevedo",
    "Urdaneta",
    "Ventanas",
    "Vinces",
    "Palenque",
    "Buena Fe",
    "Valencia",
    "Mocache",
    "Quinsaloma",
  ],
  "Manab\u00ed": [
    "Portoviejo",
    "Bol\u00edvar",
    "Chone",
    "El Carmen",
    "Flavio Alfaro",
    "Jipijapa",
    "Jun\u00edn",
    "Manta",
    "Montecristi",
    "Paj\u00e1n",
    "Pichincha",
    "Rocafuerte",
    "Santa Ana",
    "Sucre",
    "Tosagua",
    "24 de Mayo",
    "Pedernales",
    "Olmedo",
    "Puerto L\u00f3pez",
    "Jama",
    "Jaramij\u00f3",
    "San Vicente",
  ],
  "Morona Santiago": [
    "Morona",
    "Gualaquiza",
    "Lim\u00f3n Indanza",
    "Palora",
    "Santiago",
    "Suc\u00faa",
    "Huamboya",
    "San Juan Bosco",
    "Taisha",
    "Logro\u00f1o",
    "Pablo Sexto",
    "Tiwintza",
    "Sevilla Don Bosco",
  ],
  Napo: [
    "Tena",
    "Archidona",
    "El Chaco",
    "Quijos",
    "Carlos Julio Arosemena Tola",
  ],
  Pastaza: ["Pastaza", "Mera", "Santa Clara", "Arajuno"],
  Pichincha: [
    "Quito",
    "Cayambe",
    "Mej\u00eda",
    "Pedro Moncayo",
    "Rumi\u00f1ahui",
    "San Miguel de los Bancos",
    "Pedro Vicente Maldonado",
    "Puerto Quito",
  ],
  Tungurahua: [
    "Ambato",
    "Ba\u00f1os de Agua Santa",
    "Cevallos",
    "Mocha",
    "Patate",
    "Quero",
    "San Pedro de Pelileo",
    "Santiago de P\u00edllaro",
    "Tisaleo",
  ],
  "Zamora Chinchipe": [
    "Zamora",
    "Chinchipe",
    "Nangaritza",
    "Yacuambi",
    "Yantzaza",
    "El Pangui",
    "Centinela del C\u00f3ndor",
    "Palanda",
    "Paquisha",
  ],
  "Gal\u00e1pagos": ["San Crist\u00f3bal", "Isabela", "Santa Cruz"],
  "Sucumb\u00edos": [
    "Lago Agrio",
    "Gonzalo Pizarro",
    "Putumayo",
    "Shushufindi",
    "Sucumb\u00edos",
    "Cascales",
    "Cuyabeno",
  ],
  Orellana: [
    "Francisco de Orellana",
    "Aguarico",
    "La Joya de los Sachas",
    "Loreto",
  ],
  "Santo Domingo de los Ts\u00e1chilas": ["Santo Domingo", "La Concordia"],
  "Santa Elena": ["Santa Elena", "La Libertad", "Salinas"],
} as const satisfies Record<string, readonly string[]>;

export type ProvinceWithCantons = keyof typeof CANTONS_BY_PROVINCE;

const comparable = (value: string) =>
  value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim()
    .toLowerCase();

export function cantonsForProvince(province: string): readonly string[] {
  if (!Object.hasOwn(CANTONS_BY_PROVINCE, province))
    return [];
  return CANTONS_BY_PROVINCE[province as ProvinceWithCantons];
}

export function officialCanton(province: string, value: string): string | null {
  const requested = comparable(value);
  return (
    cantonsForProvince(province).find(
      (canton) => comparable(canton) === requested,
    ) ?? null
  );
}

export function cantonError(province: string, value: string): string | null {
  if (!value.trim()) return null;
  if (!province) return "Elige una provincia antes del cant\u00f3n.";
  return officialCanton(province, value)
    ? null
    : "Elige un cant\u00f3n de la provincia seleccionada.";
}
